// <auto-generated />
namespace PhoneStore.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class update_ProductMap : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_ProductMap));
        
        string IMigrationMetadata.Id
        {
            get { return "201506150812048_update_ProductMap"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
