// <auto-generated />
namespace PhoneStore.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_Discount : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_Discount));
        
        string IMigrationMetadata.Id
        {
            get { return "201506150832523_add_Discount"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
